name: CD

# main branch에 push 되면 실행
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # action이 구동될 OS 환경을 세팅
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node # action이 구동될 Node 버전을 세팅함
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Set Secret ENV
        run: echo "${{ secrets.ENV_VARS }}" > .env

      - name: Set Public ENV
        run: |
          echo "NEXT_PUBLIC_CLAUDE_PROLOGUE=/api/claude/prologue" >> .env
          echo "NEXT_PUBLIC_CLAUDE_CONTINUE=/api/claude/continue" >> .env
          echo "NEXT_PUBLIC_SCENARIO=/api/mongodb/scenario" >> .env
          echo "NEXT_PUBLIC_STORY=/api/mongodb/story" >> .env
          echo "NEXT_PUBLIC_BOOKMARK=/api/mongodb/bookmark" >> .env

      - name: Yarn install for build # 빌드를 위해 모든 패키지 설치
        run: |
          corepack enable
          yarn set version 4.3.1
          yarn install

      - name: Build project
        run: yarn build

      - name: Yarn install for production # 설치한 모든 패키지를 제거하고, dependency 패키지만 설치
        run: |
          rm -rf .yarn
          yarn workspaces focus --production

      - name: make zip file # 필요없는 디렉토리를 제외한 소스번들 압축
        run: zip -r app.zip . -x "./app.zip" -x ".git/*" -x ".github/*" -x ".vscode/*"

      - name: Deploy to EB # Elastic Beanstalk으로 배포를 진행한다.
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: textrogue
          environment_name: textrogue
          version_label: ${{ github.run_number }}
          region: ap-northeast-2
          deployment_package: app.zip
          use_existing_version_if_available: true
