name: CD

# main branch에 push 되면 실행
on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest # action이 구동될 OS 환경을 세팅
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node # action이 구동될 Node 버전을 세팅함
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Set Secret ENV
        run: echo "${{ secrets.ENV_VARS }}" > .env
      
      - name: Set Public ENV
        run: |
          echo "NEXT_PUBLIC_CLAUDE_PROLOGUE=/api/claude/prologue" >> .env
          echo "NEXT_PUBLIC_CLAUDE_CONTINUE=/api/claude/continue" >> .env
          echo "NEXT_PUBLIC_SCENARIO=/api/mongodb/scenario" >> .env
          echo "NEXT_PUBLIC_STORY=/api/mongodb/story" >> .env
          echo "NEXT_PUBLIC_BOOKMARK=/api/mongodb/bookmark" >> .env
    
      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
      
      - name: make zip file # node modules 제외한 압축 파일을 만들어준다.
        run: zip -r app.zip * -x "node_modules/*"

      - name: Deploy to EB # Elastic Beanstalk으로 배포를 진행한다.
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: TextRogue
          environment_name: TextRogue
          version_label: ${{ github.sha }}
          region: ap-northeast-2
          deployment_package: app.zip 
