name: DEPLOY_TEST

# main branch에 push 되면 실행
on:
  push:
    branches:
      - fix/deploy
    
jobs:
  deploy:
    runs-on: ubuntu-latest # action이 구동될 OS 환경을 세팅
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node # action이 구동될 Node 버전을 세팅함
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
    
      - name: Install dependencies
        run: yarn install --ignore-scripts
      
      - name: Remove .next
        run: |
          rm -rf .next

      - name: Set Secret ENV
        run: echo "${{ secrets.ENV_VARS }}" > .env
      
      - name: Set Public ENV
        run: |
          echo "NEXT_PUBLIC_CLAUDE_PROLOGUE=/api/claude/prologue" >> .env
          echo "NEXT_PUBLIC_CLAUDE_CONTINUE=/api/claude/continue" >> .env
          echo "NEXT_PUBLIC_SCENARIO=/api/mongodb/scenario" >> .env
          echo "NEXT_PUBLIC_STORY=/api/mongodb/story" >> .env
          echo "NEXT_PUBLIC_BOOKMARK=/api/mongodb/bookmark" >> .env

      - name: Build project
        run: yarn build
      
      - name: make zip file # node modules 제외한 압축 파일을 만들어준다.
        run: zip ./app.zip -r * .[^.]*

      - name: Deploy to EB # Elastic Beanstalk으로 배포를 진행한다.
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: textrogue
          environment_name: textrogue
          version_label: ${{ github.run_number }}
          region: ap-northeast-2
          deployment_package: ./app.zip 
          use_existing_version_if_available: true
